language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew :tooltipsqueue:test

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle